name: test build
on:
  push:
    tags: 
      - "**"
  workflow_dispatch:   

env:
  VERSION:
    
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - run: bun install
      - run: bun run build
    
  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: get_version
        name: get Package Version
        run: |
          echo "version=$(jq -c '.version' package.json)" >> "$GUTHUB_OUTPUT"
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.get_version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

        